#ifndef __TIAGO_SPNAV_TELEOP_HPP__
#define __TIAGO_SPNAV_TELEOP_HPP__

#include <array>
#include <memory> // std::unique_ptr
#include <mutex>
#include <utility> // std::pair
#include <vector>
#include <controller_interface/controller_interface.hpp>
#include <sensor_msgs/msg/joy.hpp>
#include "kdl/chainiksolver.hpp"
#include <kdl/jntarray.hpp>

// auto-generated by generate_parameter_library
#include "tiago_spnav_teleop/tiago_spnav_teleop_parameters.hpp"

namespace spnav_controller
{

class SpnavController : public controller_interface::ControllerInterface
{
public:
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::return_type update(const rclcpp::Time & time, const rclcpp::Duration & period) override;

  controller_interface::CallbackReturn on_init() override;
  controller_interface::CallbackReturn on_configure(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_cleanup(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_shutdown(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_activate(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_deactivate(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_error(const rclcpp_lifecycle::State & previous_state) override;

private:
  bool checkReturnCode(int ret);
  void spnavCallback(const sensor_msgs::msg::Joy::SharedPtr msg);

  std::shared_ptr<ParamListener> param_listener;
  Params params;

  std::vector<std::pair<double, double>> arm_joint_limits;

  std::array<float, 6> joy_axes;
  std::array<int, 2> joy_buttons;

  std::unique_ptr<KDL::ChainIkSolverVel> ik_solver_vel;

  KDL::JntArray q;

  rclcpp::Subscription<sensor_msgs::msg::Joy>::SharedPtr spnav_subscription;
  std::mutex mtx;
};

} //namespace

#endif // __TIAGO_SPNAV_TELEOP_HPP__
